### PR TITLE
Marlin constants functionality

### PR DESCRIPTION
**Pull request by rete**
BEGINRELEASENOTES
- Deal with Marlin constants section : 
  - Added script to generate a Marlin constants file from calibration parameters and calibration XML file
  - Modified ILD and SiD calibration parameter script to deal with this script

ENDRELEASENOTES

### CODE REVIEW

**Comment by rete** [comment]
Pinging @protopopescu for checking the SiD parameter script

**Comment by protopopescu** [comment]
I am not sure I understand what this does ...

**Comment by rete** [comment]
We have introduced in Marlin a feature where you can use constants : 
https://github.com/iLCSoft/Marlin/pull/20
It is possible to externalize the calibration constants in a separate file using also the new include feature : 
https://github.com/iLCSoft/Marlin/pull/19
The new script added here, make use able to generate a simple calibration constant file and refer to it in the top-level steering file, e.g : 
- top-level steering file : https://github.com/iLCSoft/ILDConfig/blob/master/StandardConfig/production/MarlinStdReco.xml#L73
- constant file : https://github.com/iLCSoft/ILDConfig/blob/master/StandardConfig/production/Calibration/Calibration_ILD_l4_o1_v02.xml

**Comment by rete** [comment]
@protopopescu Can we merge this PR ?

**Comment by protopopescu** [comment]
Yes, please go ahead. I will add software compensation to sid-calibration-parameters.py later on.

**Pull request merged**
